#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DIRAC/ProductionManagementSystem/scripts/Attic/dirac-production-manager-cli,v 1.1 2008/04/17 15:07:24 rgracian Exp $
# File :   dirac-production-manager-cli
# Author :  Gennady G. Kuznetsov
########################################################################
__RCSID__   = "$Id: dirac-production-manager-cli,v 1.1 2008/04/17 15:07:24 rgracian Exp $"
__VERSION__ = "$Revision: 1.1 $"

from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script
from DIRAC.ProductionManagementSystem.Client.ProductionManagerCLI import CSCLI


Script.localCfg.addDefaultEntry( "LogLevel", "DEBUG" )
Script.parseCommandLine()


ProductionManagerCLI().cmdloop()
