# This gitlab ci tests, deploys and build the docker images
# It performs some operations with an account.
# Its credentials are stored as secret variable KRB_PASSWORD and KRB_USERNAME
stages:
   # Run all the tests
  - test
  # deploy the coverage results
  - coverage
  - coverageDfs
  # Release the software on AFS
  - release
  # Build the docker
  - release_docker

# Common configuration between pytest and pylint
.test_setup: &test_setup
  image:  gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  before_script:
    # If we are in a pre release branch we use integration of DIRAC, otherwise master
    # We do the head first because of limitations of grep when running in containers
    - diracBranch=$(head -n 50 LHCbDIRAC/releases.cfg | grep -E ' *v' | head -n 1 | grep -q pre; if [ $? -eq 0 ]; then echo "integration"; else echo "master"; fi)
    - echo "Using DIRAC branch $diracBranch"
    - git clone https://github.com/DIRACGrid/DIRAC.git
    - cd DIRAC
    - git checkout $diracBranch
    - cd ..
    - yum install -y mysql mysql-libs mysql-devel make ncurses-devel
    - pip install --upgrade setuptools
    - pip install --upgrade pip
    - pip install -r DIRAC/requirements.txt

  stage: test
  only:
    - branches

# This runs pylint and fails if there are errors
run_pylint:
  <<: *test_setup
  script:
    - cd LHCbDIRAC
    - 'find . -name "*.py" -and -not -name "NotForJenkins_Test_BKK_DB_OracleBookkeepingDB.py" -exec pylint -E --rcfile=$CI_PROJECT_DIR/DIRAC/.pylintrc --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --extension-pkg-whitelist=GSI,numpy {} +'

# This runs pytest and generates the coverage report
run_pytest:
  <<: *test_setup
  script:
    - cd LHCbDIRAC
    - pytest . --cov=. --cov-report term-missing --cov-report html --junitxml=pytests.xml
  coverage: '/\d+\%\s*$/'
  artifacts:
    paths:
      - LHCbDIRAC/htmlcov/

# This runs pycodestyle
run_pycodestyle:
  <<: *test_setup
  script:
    - lhcbDiracBranch=$(head -n 50 LHCbDIRAC/releases.cfg | grep -E ' *v' | head -n 1 | grep -q pre; if [ $? -eq 0 ]; then echo "devel"; else echo "master"; fi)
    - git remote add GL https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC.git
    - git fetch --no-tags GL 
    - git branch -avv
    - git diff -U0 GL/${lhcbDiracBranch} | pycodestyle --diff

# This job MUST be call pages as per https://docs.gitlab.com/ce/ci/yaml/README.html#pages
pages:
  stage: coverage
  dependencies:
    - run_pytest
  script:
    - TARGET_DIR="public/${CI_COMMIT_REF_NAME}"
    - if [ ! -d "$TARGET_DIR" ]; then mkdir -p $TARGET_DIR; fi
    - echo "Copying into $TARGET_DIR"
    - mv LHCbDIRAC/htmlcov/* $TARGET_DIR
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
    - devel

# Deploy the pages generated to DFS
dfsdeploy:
  # Executed during the deploy stage
  stage: coverageDfs
  # # Only when the master branch is pushed
  only:
    - master
    - devel
  # Custom docker image providing the needed tools to deploy in DFS
  image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
  script:
  # Script that performs the deploy to DFS. Makes use of the variables defined in the project
  # It will not sync the generated content with the folder in DFS (risk of deleting DFS management files)
  # It will just override the contents of DFS or copy new files
  - deploy-dfs
  # do not run any globally defined before_script or after_script for this step
  before_script: []
  after_script: []



# This creates and deploy the tarball on AFS
# It is triggered with a tag only
create_tarball:
  before_script:
    # Fetch a Kerberos token
    - echo "${KRB_PASSWORD}" | kinit ${KRB_USERNAME}@CERN.CH
    # Get the group_login to be able to use lb-run
    - source /cvmfs/lhcb.cern.ch/group_login.sh
    # Configure ssh to use kerberos
    - mkdir /root/.ssh
    - echo -e  "PreferredAuthentications=gssapi-with-mic\nStrictHostKeyChecking=no\nHost lxplus*\n\tForwardX11Trusted yes\n\tGSSAPITrustDns yes\n\tGSSAPIDelegateCredentials yes\n\tGSSAPIAuthentication yes\n" > /root/.ssh/config
    # Configure git to use kerberos
    - git config --global http.emptyAuth true
  stage: release
  tags:
    # We need a runner with CVMFS
    - cvmfs
  only:
    - tags
  script:

    # Choose from which branch we should get the releases.cfg file
    # We take it from devel if it is a pre release, otherwise master
    - BRANCH=$(echo $CI_COMMIT_TAG | grep -qE '(pre|^v0r)'; if [ $? -eq 0 ]; then echo "devel"; else echo "master"; fi)
    # Get the releases.cfg from the devel branch
    - curl -L https://gitlab.cern.ch/lhcb-dirac/LHCbDIRAC/raw/$BRANCH/LHCbDIRAC/releases.cfg > releases.cfg
    # This is how it was originaly retrieved....
    #- git archive --remote  ${CI_PROJECT_DIR} origin/devel LHCbDIRAC/releases.cfg  | tar -x -v -f - --transform 's|^LHCbDIRAC/||' LHCbDIRAC/releases.cfg
    # use the kerberos gitlab auth rather than ssh
    - sed 's/ssh:\/\/git@gitlab.cern.ch:7999/https:\/\/:@gitlab.cern.ch:8443/g' -i releases.cfg
    # Create the release tarball
    # The last line output by the script is the command to run in order to deploy
    - lb-run LHCbDIRAC/prod dirac-distribution -r ${CI_COMMIT_TAG} -l LHCb -C file:///$(pwd)/releases.cfg | tail -n 1  > /tmp/deploy.sh
    # Use the proper user
    - sed "s/lhcbprod/${KRB_USERNAME}/g" -i /tmp/deploy.sh
   #  # FIXME: this is the wrong path, but is used as a test
   #  - sed 's/\/afs\/cern.ch\/lhcb\/distribution\/LHCbDirac_project/\/afs\/cern.ch\/user\/l\/lbmesos/g' -i /tmp/deploy.sh
    # There are not html and pdf file, so the script returns a non 0 code, despite working fine
    - sed 's/\*.pdf \*.html//g' -i /tmp/deploy.sh
    - cat /tmp/deploy.sh
    # Execute the deployment
    - source /tmp/deploy.sh



# When we have a git tag, after creating the tarball, create the docker image
build_docker_image:
  tags:
    - docker-image-build
  stage: release_docker
  only:
    - tags
  # This needs to be there for gitlab
  script: echo ""
  variables:
    TO: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
    CONTEXT_DIR: ${CI_PROJECT_DIR}/container/lhcbdirac/
