#!/bin/bash
#****** gRB/gRB-sft-submit
# NAME
# gRB-sft-submit - checks:
# * glite-wms-job-delegate-proxy
# * glite-wms-job-submit
# * glite-wms-job-status
# * glite-wms-job-output
# * glite-wms-job-logging-info
#
# AUTHOR
#
# Malgorzata Krakowian 
#
# LAST UPDATED
#
# 09-11-2007
#
# LANGUAGE
#
# bash
#
# SOURCE


function exitonerr {
    grep -q "System load is too high" $log
    if [ "$?" == "0" ]; then
    	if [ "$inMaintenance" == "Y" ] ; then
        	exit $SAME_MAINTENANCE
   	fi
	exit $SAME_WARNING
    fi
    rm -f $log testjob-submit.jid glite_wms-submit.conf testjob-submit.jdl testjob.jid 
    if [ "$inMaintenance" == "Y" ] ; then
        exit $SAME_MAINTENANCE
    fi
    exit $SAME_ERROR            
}

. $SAME_SENSOR_HOME/config.sh

log="gRB-sft-submit.log"
centralCE=`cat centralCE`
inMaintenance=`cat inMaintenance`

if [ "$1" == "--publish" ] ; then
    if [ ! -e testjob.jid ] ; then 
        exit 0
    fi

    jobStatus=`$JOB_STATUS_CMD -i testjob.jid `
    if [ "$?" != "0" ]; then
        echo "<h2>Glite-wms-job-status</h2>" >> $log
        echo "<pre>" >> $log
        exec 3>&1 4>&2 1>>$log 2>&1
        set -x
        $JOB_STATUS_CMD  -i  testjob.jid
        set +x
        exec 1>&- 1>&3 2>&4 3>&- 4>&-
        echo "</pre>" >> $log
        cat $log        
        echo "Job status failed! Check the Resource Broker"
        exitonerr
    fi

    if [ "`echo $jobStatus | grep -E 'Done\ \(Success\)'`" ] ; then # job ended succesfuly     :D
        echo "<h2>Glite-wms-job-status</h2>" >> $log
        echo "<pre>" >> $log
        exec 3>&1 4>&2 1>>$log 2>&1
        set -x
        $JOB_STATUS_CMD  -i  testjob.jid
        RESULT=$?
        set +x
        exec 1>&- 1>&3 2>&4 3>&- 4>&-
        echo "</pre>" >> $log
        if [ "$RESULT" != "0" ]; then  # if failed       :(
            cat $log        
            echo "Job status failed! Check the Resource Broker"
            exitonerr
        fi

#removing job-get-output part

#        echo "<h2>Glite-wms-job-output</h2>" >> $log
#        echo "<pre>" >> $log
#        exec 3>&1 4>&2 1>>$log 2>&1
#        set -x
#        $JOB_OUTPUT_CMD  -c glite_wms-submit.conf -i  testjob.jid
#        RESULT=$?
#        set +x
#        exec 1>&- 1>&3 2>&4 3>&- 4>&-
#        echo "</pre>" >> $log

#        if [ "$RESULT" != "0" ]; then  # if failed :(
#            cat $log        
#            echo "Job get output failed! Check the Resource Broker"
#            exitonerr
#        fi

#        echo "<h2>Job output</h2>" >> $log
#	OUT=`cat ${USER}_*/testjob.out`
#       	echo "<pre>" >> $log
#       	echo "> cat ${USER}_*/testjob.out" >> $log
#       	echo $OUT >> $log
#       	echo "</pre>" >> $log
#       	if [ "$OUT" == "SAM" ]; then 
#        		echo "Job output correct" >> $log   
#         		exitonerr=0;
#       	else
#            		echo "Job output incorrect"
#            		exitonerr=1;
#       	fi 

        echo "<h2>Glite-wms-job-logging-info</h2>" >> $log
        echo "<pre>" >> $log
        exec 3>&1 4>&2 1>>$log 2>&1
        set -x
        $JOB_LOGGING_INFO_CMD -i testjob.jid
        RESULT=$?
        set +x
        exec 1>&- 1>&3 2>&4 3>&- 4>&-
        echo "</pre>" >> $log

        if [ "$RESULT" != "0" ]; then  # if failed :(
            cat $log        
            echo "Job logging info failed! Check the Resource Broker"
            exitonerr
        fi

        cat $log   
        if [ $exitonerr == "1" ]; then
		exitonerr
	   fi

        rm -f $log testjob.jid 
	    if [ "$inMaintenance" == "Y" ] ; then
	  	  exit $SAME_MAINTENANCE
	    fi
        exit $SAME_OK                                                                                                                           
    fi

    if [ "`echo $jobStatus | grep -E 'Aborted|Done\ \(Failed\)'`" ] ; then
        echo "<h2>Glite-wms-job-status</h2>" >> $log
        echo "<pre>" >> $log
        exec 3>&1 4>&2 1>>$log 2>&1
        set -x
        $JOB_STATUS_CMD  -i  testjob.jid
        RESULT=$?
        set +x
        exec 1>&- 1>&3 2>&4 3>&- 4>&-
        echo "</pre>" >> $log
        if [ "$RESULT" != "0" ]; then  # if failed       :(
            cat $log        
            echo "Job status failed! Check the Resource Broker"
            exitonerr
        fi

        echo "<h2>Glite-wms-job-logging-info</h2>" >> $log
        echo "<pre>" >> $log
        exec 3>&1 4>&2 1>>$log 2>&1
        set -x
        $JOB_LOGGING_INFO_CMD -i testjob.jid
        RESULT=$?
        set +x
        exec 1>&- 1>&3 2>&4 3>&- 4>&-
        echo "</pre>" >> $log

        if [ "$RESULT" != "0" ]; then  # if failed    :(
            cat $log        
            echo "Job logging info failed! Check the Resource Broker"
            exitonerr
        fi
        cat $log     
        rm -f $log testjob.jid 
        if [ "$inMaintenance" == "Y" ] ; then
          exit $SAME_MAINTENANCE
        fi
        exit $SAME_OK
    fi
                                                                    
    exit 0  # job not finished, get rest
else  # submit
    if [ -e testjob.jid ] ; then
	   # job exists, do nothing, get rest
        exit 0
 fi

    siteName=$1
    nodeName=$2
    
    # clean your room pumpkin'
    rm -f $log testjob.jid glite_wms-submit.conf  testjob-submit.jdl   
    rm -rf ${USER}_*

    echo "<h2>Generating JDL file:</h2>" >> $log
    sed  -e "s/<centralCE>/$centralCE/g" $SAME_SENSOR_HOME/testjob.jdl > testjob-submit.jdl
    echo "<pre>" >> $log
    cat testjob-submit.jdl >> $log
    echo "</pre>" >> $log
    echo "<h2>Generating glite_wms.conf file:</h2>" >> $log
    sed  -e "s/<nodeName>/$nodeName/g" -e "s/<SAME_VO>/$SAME_VO/g" -e "s|<SAME_SENSOR_WORK>|$SAME_SENSOR_WORK|g"  $SAME_SENSOR_HOME/glite_wms.conf > glite_wms-submit.conf 
    echo "<pre>" >> $log
    cat glite_wms-submit.conf >> $log
    echo "</pre>" >> $log

    echo "<h2>Glite-wms-job-delegate-proxy</h2>" >> $log
    echo "<pre>" >> $log
    exec 3>&1 4>&2 1>>$log 2>&1
    set -x
    $JOB_DELEGATE_CMD  -d $nodeName -c glite_wms-submit.conf
    RESULT=$?
    set +x
    exec 1>&- 1>&3 2>&4 3>&- 4>&-
    echo "</pre>" >> $log
    if [ "$RESULT" != "0" ] ; then
           echo "Proxy delegation failed! Check the Resource Broker" >> $log
           echo "summary: DelegationError" >> $log
           cat $log
           exitonerr
    fi

    echo "<h2>Glite-wms-job-submit</h2>" >> $log
    echo "<pre>" >> $log
    exec 3>&1 4>&2 1>>$log 2>&1
    set -x
    $JOB_SUBMIT_CMD -d $nodeName -c glite_wms-submit.conf -o testjob.jid testjob-submit.jdl
    set +x
    exec 1>&- 1>&3 2>&4 3>&- 4>&-
    echo "</pre>" >> $log
    if [ ! -e testjob.jid ] ; then
        echo "Job submission failed! Check the Resource Broker" >> $log
        echo "summary: SubmitError" >> $log
        cat $log
        exitonerr
    fi
    exit 0
fi
#****
