<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://lcg-sam.cern.ch:8080/same-ws/services/WebArchiver" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://lcg-sam.cern.ch:8080/same-ws/services/WebArchiver" xmlns:intf="http://lcg-sam.cern.ch:8080/same-ws/services/WebArchiver" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on May 14, 2006 (10:28:20 EDT)-->

   <wsdl:message name="gvInsertDataResponse">

      <wsdl:part name="gvInsertDataReturn" type="xsd:int"/>

   </wsdl:message>

   <wsdl:message name="gvInsertDataRequest">

      <wsdl:part name="schemaName" type="xsd:string"/>

      <wsdl:part name="tupleCount" type="xsd:int"/>

      <wsdl:part name="dataLength" type="xsd:int"/>

      <wsdl:part name="data" type="xsd:string"/>

   </wsdl:message>

   <wsdl:portType name="WebArch">

      <wsdl:operation name="gvInsertData" parameterOrder="schemaName tupleCount dataLength data">

         <wsdl:input message="impl:gvInsertDataRequest" name="gvInsertDataRequest"/>

         <wsdl:output message="impl:gvInsertDataResponse" name="gvInsertDataResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="WebArchiverSoapBinding" type="impl:WebArch">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="gvInsertData">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="gvInsertDataRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://arch.gview" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="gvInsertDataResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://lcg-sam.cern.ch:8080/same-ws/services/WebArchiver" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="WebArchService">

      <wsdl:port binding="impl:WebArchiverSoapBinding" name="WebArchiver">

         <wsdlsoap:address location="http://lcg-sam.cern.ch:8080/same-ws/services/WebArchiver"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
