#!/bin/bash

#
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/DiracSys/dirac-make,v 1.2 2009/10/05 06:13:08 rgracian Exp $
#
# preliminary version to prepare external package needed for DIRAC3
#
function canonicalize
{
  cd -P -- "$(dirname -- "$1")" &&
  printf '%s\n' "$(pwd -P)/$(basename -- "$1")"
}
basedir=`canonicalize $0`
basedir=`dirname $basedir`
basedir=`canonicalize $basedir/..`
#
#DIRACdir=`canonicalize $basedir/..`
cd $basedir

tar zxvf $LHCBTAR/DIRAC3/DIRAC-external-client-v4r0-${DIRACPLAT}-python25.tar.gz $DIRACPLAT/lib/python2.5/site-packages/GSI/

if ! [ -r $basedir/InstallArea/scripts ]; then
  ln -s ../scripts $basedir/InstallArea/scripts
fi

if ! [ -r $basedir/InstallArea/python ]; then
  ln -s ../ $basedir/InstallArea/python
fi

if ! [ -r $basedir/InstallArea/$CMTCONFIG/python2.5 ]; then
  mkdir $basedir/InstallArea/$CMTCONFIG/python2.5
fi

ln -s ../../../$DIRACPLAT/lib/python2.5/site-packages/GSI $basedir/InstallArea/$CMTCONFIG/python2.5/

$basedir/scripts/dirac-configure -S LHCb-Production -C dips://lhcbprod.pic.es:9135/Configuration/Server

touch $basedir/LHCbDIRAC/__init__.py

if ! [ -r $basedir/etc/vomses ]; then
  mkdir $basedir/etc/vomses
fi

cat > $basedir/etc/vomses/lhcb <<EOF
"lhcb" "voms.cern.ch" "15003" "/DC=ch/DC=cern/OU=computers/CN=voms.cern.ch" "lhcb" "24"
EOF

