#!/usr/bin/env python
########################################################################
# $Id: $
########################################################################

from DIRAC.Interfaces.API.Dirac                       import Dirac
from DIRAC.BookkeepingSystem.Client.LHCB_BKKDBClient  import LHCB_BKKDBClient
from DIRAC.Core.Base import Script

__RCSID__ = "$Id: $"

Script.parseCommandLine( ignoreErrors = True )
args = Script.getPositionalArgs()


cl = LHCB_BKKDBClient()
path = args[0]

print cl.list(path)

