#!/bin/bash
#
#$Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/scripts/Attic/dirac-embedded-external,v 1.2 2007/07/11 14:20:19 rgracian Exp $
#
# preliminary version to prepare external package needed for DIRAC3 with embedded MySQL server
# 
# __RCSID__='$Id: dirac-embedded-external,v 1.2 2007/07/11 14:20:19 rgracian Exp $'

source `dirname $0`/dirac-functions.sh

echo
echo "Preparing DIRAC distribution at ${TMP_DIR}"
echo
echo "  type any password"
echo

DIRAC_CVS_GET DIRAC3/scripts                                             || exit 1
export arch=`DIRAC3/scripts/dirac-architecture`
echo
echo "   building DIRAC-external from CVS tag ${DIRAC_CVS_TAG} for architecture: ${arch}"
echo

DIRAC_MAKE    DIRAC3/external/Python-2.4.4                               || exit 1

export PATH="${TMP_DIR}/DIRAC3/${arch}/bin:$PATH"

DIRAC_MAKE    DIRAC3/external/runit                                      || exit 1

DIRAC_CVS_GET DIRAC3/external/openssl-0.9.7m                             || exit 1
DIRAC_MAKE    DIRAC3/contrib/pyOpenSSL                                   || exit 1

DIRAC_MAKE    DIRAC3/external/MySQL-embedded                             || exit 1

DIRAC_MAKE    DIRAC3/external/MySQL-embedded-python                      || exit 1

tarfile1=DIRAC-embedded-external-${DIRAC_CVS_TAG}.${arch}-python24.tar.gz
DIRAC_TAR     ${tarfile1} etc ${arch}                                    || exit 1

echo
echo
echo "scp ${TMP_DIR}/DIRAC3/${tarfile1} lhcbprod@lxplus.cern.ch:/afs/cern.ch/lhcb/distribution/production_tools"
echo
echo

rm -rf DIRAC3/${arch}

#
#  Only python packages need to be recompiled.
#  MySQL needs to be reinstalled, but will not be recompiled
#

DIRAC_MAKE    DIRAC3/external/Python-2.5                                 || exit 1

# export PATH="${TMP_DIR}/DIRAC3/${arch}/bin:$PATH"

DIRAC_INSTALL DIRAC3/external/runit                                      || exit 1

DIRAC_INSTALL DIRAC3/contrib/pyOpenSSL                                   || exit 1

DIRAC_INSTALL DIRAC3/external/MySQL-embedded                             || exit 1

DIRAC_MAKE    DIRAC3/external/MySQL-embedded-python                      || exit 1

tarfile1=DIRAC-embedded-external-${DIRAC_CVS_TAG}.${arch}-python25.tar.gz
DIRAC_TAR     ${tarfile1} etc ${arch}                                    || exit 1

tarfile2=DIRAC-embedded-contrib-${DIRAC_CVS_TAG}.${arch}.tar.gz
DIRAC_TAR     ${tarfile2} contrib/python*                                || exit 1

echo
echo
echo "scp ${TMP_DIR}/DIRAC3/${tarfile1} lhcbprod@lxplus.cern.ch:/afs/cern.ch/lhcb/distribution/production_tools"
echo
echo "scp ${TMP_DIR}/DIRAC3/${tarfile2} lhcbprod@lxplus.cern.ch:/afs/cern.ch/lhcb/distribution/production_tools"
echo
echo


exit
