#!/bin/bash
#
#$Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/scripts/Attic/dirac-clean,v 1.1 2007/05/18 10:23:31 rgracian Exp $
#
# preliminary version to prepare external package needed for DIRAC3
# 
# __RCSID__='$Id: dirac-clean,v 1.1 2007/05/18 10:23:31 rgracian Exp $'

source `dirname $0`/dirac-functions.sh

basedir=`readlink -f $0`
basedir=`dirname $basedir`

cd $basename/..

echo
echo "cleaning DIRAC tree"
echo
[ -x DIRAC/dirac_clean ] && DIRAC/dirac_clean

echo
echo "cleaning external tree"
echo
for dir in `find external -maxdepth 1 -type d`; do
  [ -x $dir/dirac_clean ] && $dir/dirac_clean
done

echo
echo "cleaning contrib tree"
echo
for dir in `find contrib -maxdepth 1 -type d`; do
  [ -x $dir/dirac_clean ] && $dir/dirac_clean
done


exit
