#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/scripts/Attic/dirac-update,v 1.14 2008/03/26 15:23:40 rgracian Exp $
# File :   dirac-update
# Author : Ricardo Graciani
########################################################################
__RCSID__   = "$Id: dirac-update,v 1.14 2008/03/26 15:23:40 rgracian Exp $"
__VERSION__ = "$Revision: 1.14 $"
"""
    Script to prepare/update a DIRAC instalation
"""

from dirac_functions import *

myFullName  = os.path.realpath( __file__ )
myShortName = os.path.basename( myFullName )

rootPath = logInit( myFullName )


tarFlag()

platform = get_platform( )

def parse_options():
  """
   parse command line options:
  """
  global platform, rootPath
  help = """
   -b --build                  Force local compilation
   -d --debug                  Set debug flag
   -e --external=<version>     DIRAC-external <version> to install (overwrites -v)
   -h --help                   Print this
   -i --python=<24|25>         Use python<24|25> interpreter
   -r --repository=<rep>       Use <rep> as cvs repository
   -p --platform=<platform>    Use <platform> instead of local one
   -u --url=<url>              Use <url> to download tarballs
   -v --version=<version>      DIRAC <version> to install
   -C --cvs                    Retrieve from CVS (implies -b)
   -P --path=<root>            Install under <root>

  from DIRAC framework:

    -o --option=<Option=value> <Option=value> to add
    -s --section=<section>     Set base <section> for relative parsed options
    -c --cert=<cert>           Use server certificate <cert> to connect to Core Services

  """
  shortOptions = 'bde:hi:p:u:v:o:s:CP:'
  longOptions  = ['build', 'debug', 'external=', 'help', 'python=', 'platform=', 'url=', 'version=', 
                  'cvs', 'path=',
                  'option=', 'section=']
  try:
    ( optionVals, extraOptions ) = getopt.getopt( sys.argv[1:], shortOptions, longOptions )
  except getopt.GetoptError, x:
    logERROR( 'Parsing command line: %s' % x )
    optionVals = [ ('-h','') ]

  if ('-h','') in optionVals or ('--help','') in optionVals:
    logHelp( help )

  ext = None
  for o,v in optionVals:
    if o == '-b' or o == '--build':
      build()
    elif o == '-d' or o == '--debug':
      debug()
    elif o == '-e' or o == '--external':
      ext = v
    elif o == '-i' or o == '--python':
      set_python(v)
    elif o == '-p' or o == '--platform':
      platform = set_platform(v)
    elif o == '-r' or o == '--repository':
      default_CVS(v)
    elif o == '-u' or o == '--url':
      default_URL( v )
    elif o == '-v' or o == '--version':
      version(v)
    elif o == '-C' or o == '--cvs':
      cvsFlag()
    elif o in ('-P', '--path'):
      rootPath = logInit( os.path.join( v, 'scripts', myShortName ) )

    if ext: external(ext)


parse_options()
logINFO( 'Checking DIRAC instalation at "%s"' %  rootPath )
logINFO( 'Using platform "%s"' %  platform )

localPython   = os.path.join( rootPath, platform, 'bin', 'python' )
if not check_interpreter( localPython ):
  install_external( platform )
  localVersion = check_dirac( defaultVersion )
  dirac_magic(  '#! %s' % localPython )
  # if we are not running with our onw python let's call ourself again
  logINFO( 'Will retry now with DIRAC python' )
  args         = str.join(' ',sys.argv[1:]) + ' -v %s' % localVersion
  myScript = os.path.join( rootPath,'scripts', myShortName )
  logDEBUG( '%s %s %s ' % ( localPython, myScript, args ) )
  ret = os.system( '%s %s %s ' % ( localPython, myScript, args ) )
  sys.exit(ret)

else:
  localVersion = check_dirac( defaultVersion )
  dirac_magic(  '#! %s' % localPython )
  from DIRACEnvironment import DIRAC
  if debugFlag:
    DIRAC.gLogger.setLevel( 'DEBUG' )
  else:
    DIRAC.gLogger.setLevel( 'INFO' )
  from DIRAC.Core.Utilities.GridCredentials import setDIRACGroup
  
  setDIRACGroup( 'lhcb_user' )
  
  from DIRAC.Core.Base import Script

  Script.registerSwitch( "b",  "build",     "Allow compilation if platform not available" )
  Script.registerSwitch( "d",  "debug",     "Set debug flag" )
  Script.registerSwitch( "e:", "external=", "DIRAC-external <version> to install" )
  Script.registerSwitch( "i:", "python=",   "Use python<24|25> interpreter" )
  Script.registerSwitch( "p:", "platform=", "Use <platform> instead of local one" )
  Script.registerSwitch( "u:", "url=",      "Use <url> to download tarballs" )
  Script.registerSwitch( "v:", "version=",  "DIRAC <version> to install" )
  Script.registerSwitch( "C",  "cvs",       "Retrieve from CVS (implies -b)" )
  Script.registerSwitch( "P:", "path=",     "Install under <root>" )
  
  from DIRAC.ConfigurationSystem.Client.LocalConfiguration import LocalConfiguration
  localCfg = LocalConfiguration()
  localCfg.addDefaultEntry( '/DIRAC/Setup', 'LHCb-Development' )
  localCfg.addDefaultEntry( '/DIRAC/Configuration/Servers',
                            'dips://lhcbprod.pic.es:9135/Configuration/Server, '
                            'dips://volhcb03.cern.ch:9135/Configuration/Server' )
  
  Script.parseCommandLine( scriptName = myShortName, ignoreErrors = True )
  
  DIRAC.gConfig.dumpLocalCFGToFile( cfgPath )
  # further checks can be implemented here
  logINFO( 'DIRAC version "%s" installed' % localVersion)
  logINFO( 'DIRAC-external version "%s" installed' % externalVersion)

  sys.exit(0)
