#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/scripts/Attic/dirac-distribution,v 1.11 2008/04/20 06:46:27 rgracian Exp $
# File :   dirac-distribution
# Author : Ricardo Graciani
########################################################################
__RCSID__   = "$Id: dirac-distribution,v 1.11 2008/04/20 06:46:27 rgracian Exp $"
__VERSION__ = "$Revision: 1.11 $"
"""
    Script to prepare DIRAC distribution tarballs
"""

def parse_options():
  """
   parse command line options:
  """
  import getopt
  help = """
   -b --build                  Prepare compile tars for local platform
   -d --debug                  Set debug flag
   -e --external=<version>     DIRAC-external <version> to install (overwrites -v)
   -h --help                   Print this
   -i --python=<24|25>         Use python<24|25>
   -r --repository=<rep>       Use <rep> as cvs repository
   -t --tar                    Retrieve from tar
   -u --url=<url>              Use <url> to download tarballs
   -v --version=<version>      DIRAC <version> to install
   -S --server                 Prepare full external tar

  from DIRAC framework:

    -o --option=<Option=value> <Option=value> to add
    -s --section=<section>     Set base <section> for relative parsed options
    -c --cert=<cert>           Use server certificate <cert> to connect to Core Services

  """
  shortOptions = 'bde:hi:p:r:tu:v:o:s:S'
  longOptions  = ['build', 'debug', 'external=', 'help', 'python=', 'repository=', 'url=', 'version=',
                  'server', 'tar',
                  'option=', 'section=']
  try:
    ( optionVals, extraOptions ) = getopt.getopt( sys.argv[1:], shortOptions, longOptions )
  except getopt.GetoptError, x:
    dirac.logERROR( 'Parsing command line: %s' % x )
    optionVals = [ ('-h','') ]

  if ('-h','') in optionVals or ('--help','') in optionVals:
    dirac.logHelp( help )

  ext = None
  for o,v in optionVals:
    if o == '-b' or o == '--build':
      dirac.build()
    elif o == '-d' or o == '--debug':
      dirac.debug()
    elif o == '-e' or o == '--external':
      ext = v
    elif o == '-i' or o == '--python':
      dirac.setPython(v)
    elif o == '-r' or o == '--repository':
      dirac.setCVS(v)
    elif o == '-u' or o == '--url':
      dirac.setURL(v)
    elif o == '-v' or o == '--version':
      dirac.setVersion(v)
    elif o == '-t' or o == '--tar':
      dirac.tarFlag()
    elif o == '-S' or o == '--server':
      dirac.requireServer()
      
    if ext: function.External(ext)

def exit( ret ):
  """
   Remove tmpDir and exit
  """
  dirac.logINFO( 'Remember to remove temporary Directory "%s"' % rootPath )
  sys.exit( ret )

import os, sys
from dirac_functions import functions
myFullName  = os.path.realpath( sys.argv[0] )
myShortName = os.path.basename( myFullName )

dirac = functions( myFullName )
# get a tmp Root path to prepare the distribution
rootPath = dirac.tmpDir()
# by default use CVS repository
dirac.cvsFlag()

parse_options()
dirac.logINFO( 'Preparing DIRAC distribution at "%s"' %  dirac.root() )
if dirac.buildFlag:
  dirac.logINFO( 'Using platform "%s"' %  dirac.localPlatform )

tars =  dirac.createSrcTars()
tars += dirac.createBinTars()

if tars > 0:
  dirac.logINFO( 'Upload tar files to repository:' )
  dirac.logINFO( ' scp %s/*.tar.gz lhcbprod@lxplus.cern.ch:/afs/cern.ch/lhcb/distribution/DIRAC3' % rootPath )

exit(0)
