#!/bin/bash
#
#$Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/scripts/Attic/dirac-external,v 1.18 2008/03/10 15:04:26 acasajus Exp $
#
# preliminary version to prepare external package needed for DIRAC3
#
# __RCSID__='$Id: dirac-external,v 1.18 2008/03/10 15:04:26 acasajus Exp $'

source `dirname $0`/dirac-functions.sh

echo
echo "Preparing DIRAC distribution at ${TMP_DIR}"
echo
echo "  type any password"
echo

DIRAC_CVS_GET DIRAC3/scripts                                             || exit 1
export arch=`DIRAC3/scripts/dirac-architecture`
echo
echo "   building DIRAC-external from CVS tag ${DIRAC_CVS_TAG} for architecture: ${arch}"
echo

DIRAC_MAKE    DIRAC3/external/Python-2.4.4                               || exit 1

export PATH="${TMP_DIR}/DIRAC3/${arch}/bin:$PATH"

DIRAC_MAKE    DIRAC3/external/runit                                      || exit 1

DIRAC_CVS_GET DIRAC3/external/openssl-0.9.7m                             || exit 1
#DIRAC_MAKE    DIRAC3/contrib/pyOpenSSL                                   || exit 1

DIRAC_CVS_GET DIRAC3/external/openssl-0.9.8g                             || exit 1
DIRAC_MAKE    DIRAC3/contrib/pyGSI                                       || exit 1

DIRAC_MAKE    DIRAC3/external/MySQL                                      || exit 1

DIRAC_MAKE    DIRAC3/external/MySQL-python                               || exit 1

DIRAC_MAKE    DIRAC3/external/Pylons                                     || exit 1

DIRAC_MAKE    DIRAC3/external/matplotlib                                 || exit 1

DIRAC_MAGIC   DIRAC3/${arch}                                             || exit 1

tarfile1=DIRAC-external-${DIRAC_CVS_TAG}.${arch}-python24.tar.gz
DIRAC_TAR     ${tarfile1} etc ${arch}                                    || exit 1

echo
echo
echo "scp ${TMP_DIR}/DIRAC3/${tarfile1} lhcbprod@lxplus.cern.ch:/afs/cern.ch/lhcb/distribution/DIRAC3"
echo
echo

rm -rf DIRAC3/${arch}

#
#  Only python packages need to be recompiled.
#  MySQL needs to be reinstalled, but will not be recompiled
#
DIRAC_MAKE    DIRAC3/external/sqlite-3.5.4                               || exit 1

DIRAC_MAKE    DIRAC3/external/Python-2.5                                 || exit 1

# export PATH="${TMP_DIR}/DIRAC3/${arch}/bin:$PATH"

DIRAC_INSTALL DIRAC3/external/runit                                      || exit 1

#DIRAC_INSTALL DIRAC3/contrib/pyOpenSSL                                   || exit 1

DIRAC_MAKE    DIRAC3/contrib/pyGSI                                       || exit 1

DIRAC_INSTALL DIRAC3/external/MySQL                                      || exit 1

DIRAC_MAKE    DIRAC3/external/MySQL-python                               || exit 1

DIRAC_MAKE    DIRAC3/external/Pylons                                     || exit 1

DIRAC_MAKE    DIRAC3/external/matplotlib                                 || exit 1

DIRAC_MAGIC   DIRAC3/${arch}                                             || exit 1

tarfile1=DIRAC-external-${DIRAC_CVS_TAG}.${arch}-python25.tar.gz
DIRAC_TAR     ${tarfile1} etc ${arch}                                    || exit 1

tarfile2=DIRAC-contrib-${DIRAC_CVS_TAG}.${arch}.tar.gz
DIRAC_TAR     ${tarfile2} contrib/python*                                || exit 1

echo
echo
echo "scp ${TMP_DIR}/DIRAC3/${tarfile1} lhcbprod@lxplus.cern.ch:/afs/cern.ch/lhcb/distribution/DIRAC3"
echo
echo "scp ${TMP_DIR}/DIRAC3/${tarfile2} lhcbprod@lxplus.cern.ch:/afs/cern.ch/lhcb/distribution/DIRAC3"
echo
echo


exit
