#!/bin/csh
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/scripts/dirac-architecture,v 1.2 2007/03/09 15:45:18 rgracian Exp $
#-----------------------------------------
# initialize CMT
#-------------------------------------
#set echo on

# set default values for CMT and gcc versions
set comp = `gcc --version | grep gcc | awk '{print $3}' | tr -d "."`
if ("$comp" >= "340") then
  set gcc = `gcc --version | grep gcc | awk '{print $3}' | awk -F. '{for(i=1; i<=2; i++){print $i}}'`
  set comp = `echo $gcc | tr -d " "`
endif

set nativehw = `uname -m`

set compdef = gcc$comp
set nativehw = `uname -m` 
[ "$nativehw" = "unknown" ] && set nativehw = `uname -p` 

#==============================================================
# deal with different linux distributions
if (-e /etc/redhat-release) then
  set distrib = `cat /etc/redhat-release | awk '{print $1}'`
  set rhv = `cat /etc/redhat-release | tr -d '[a-z][A-Z]()'`
  if ("$distrib" == "Scientific") then
    set hw = $nativehw
    if ($hw == "i?86") set hw = "ia32"
    # for the moment use ia32 even on amd64
    # if ($hw == "x86_64") set hw = "amd64"
    if ($hw == "x86_64") set hw = "ia32"
    set rhv = `echo ${rhv} | awk -F "." '{print $1}'`
    set rh = "slc"${rhv}"_"${hw}
  else
    set rhv = `echo ${rhv} | tr -d "."`
    set rh = "rh$rhv"
  endif
endif
# deal with OS type ===========================================
if ( "$OSTYPE" == "darwin" ) then
  set rh = `sw_vers | grep ProductVersion | awk '{print $2}' | awk -F. '{print $1 $2}'`
  setenv CMTOPT osx$rh
  set rh = "osx$rh"
#
else if ( "$OSTYPE" == "linux" ) then
# get the compiler from the arguments
  if ("$?newcomp" == "0") then
    set comp = $compdef
  else
    set comp = $newcomp
  endif

  if ( $nativehw == "x86_64" && $comp == "gcc323") then

    setenv CMTOPT "slc3_ia32_${comp}"
    set rh = "slc3_ia32"
  endif

  set binary =  linux_${nativehw}_${comp}
  if ($nativehw == "ia64") set binary = `echo $binary | sed -e 's/ia64/amd64/'`
  setenv CMTOPT  ${binary}
endif

setenv CMTCONFIG "${CMTOPT}"

echo $CMTCONFIG

exit 
