#!/bin/bash -i
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/scripts/dirac-bash,v 1.2 2008/10/29 11:58:04 rgracian Exp $
# File :   dirac-bash
# Author : Ricardo Graciani
# Usage : dirac-bash
########################################################################
#
[ -z "$DIRACROOT" ] && export DIRACROOT=`python -c "import os,sys ; print os.path.dirname(os.path.dirname( os.path.realpath( sys.argv[1] ) ))" $0`
[ -z "$DIRACPLAT" ] && export DIRACPLAT=`$DIRACROOT/scripts/platform.py`

export PATH=$DIRACROOT/$DIRACPLAT/bin:$PATH
if [ -z "$LD_LIBRARY_PATH" ] ; then
  export LD_LIBRARY_PATH=$DIRACROOT/$DIRACPLAT/lib
else
  export LD_LIBRARY_PATH=$DIRACROOT/$DIRACPLAT/lib:$LD_LIBRARY_PATH
fi
export PYTHONPATH=$DIRACROOT/scripts:$DIRACROOT

/bin/bash -p
