#!/usr/bin/env python
########################################################################
# $Header: /tmp/libdirac/tmp.stZoy15380/dirac/DIRAC3/scripts/Attic/dirac-update,v 1.1 2008/03/18 14:47:35 rgracian Exp $
# File :   dirac-update
# Author : Ricardo Graciani
########################################################################
