#!/bin/bash

if [ -z "$DIRACROOT" ] ; then
    echo "Variable DIRACROOT (directory containing DIRAC/) is not defined"
    exit 1
fi

if [ -z "$DIRACPYTHON" ] ; then
    echo "Variable DIRACPYTHON (path to DIRAC python executable) is not defined"
    exit 1
fi

$DIRACROOT/scripts/dirac-jobexec $1