#!/usr/bin/env python

""" Returns the architecture tag to be used for CMTCONFIG or architecture
"""

__RCSID__ = "$Id"

from DIRAC.Core.Base.Script import parseCommandLine
parseCommandLine()

import sys, platform
from DIRAC.ConfigurationSystem.Client.Helpers.Resources import getDIRACPlatform

if __name__ == "__main__" :
  dist = platform.linux_distribution()
  if not dist[0]:
    # is it mac?
    dist = platform.mac_ver()
    if not dist[0]:
      # windows, really?
      dist = platform.win32_ver()

  OS = '_'.join( dist ).replace( ' ', '' )

  res = getDIRACPlatform( '_'.join( [platform.machine(), OS] ) )
  if not res['OK']:
    print "ERROR: %s" % res['Message']
  if not res['Value']:
    print "ERROR, %s not found" % '_'.join( [platform.machine(), OS] )

  print res['Value'][0]
