#! /usr/bin/env python

from DIRACEnvironment import DIRAC
from DIRAC.Core.Base import Script


def usage():
  print 'Usage: %s [Try -h,--help for more information] job [job2 [job3 [...]]]' %(Script.scriptName)
  DIRAC.exit(2)


args = Script.getPositionalArgs()

if len(args)==0:
  usage()


from DIRAC.LHCbSystem.Utilities.JobOutputLFN import getJobOutputLFN
from DIRAC.DataManagementSystem.Client.ReplicaManager import ReplicaManager
rm = ReplicaManager()

for arg in args:
  try:
    job = int(arg)
  except:
    print "Wrong argument, job must be integer %s  "%arg
    continue
    
  result = getJobOutputLFN(job)
  if result['OK']:
    lfns = result['Value']
    replicas = rm.getReplicas(lfns)
    if replicas['OK']:
      value = replicas['Value']
      print value
  else:
    print result['Message']
