#!/bin/bash
#****** FTS/FTS-infosite
# NAME
# FTS-infosite -
#
# AUTHOR
#
# SAM Team same-devel[at]cern.ch
#
# LAST UPDATED
#
# 2007-02-06
#
# LANGUAGE
#
# bash
#
# SOURCE

nodeName=$1
echo "Checking if FTS node $nodeName is registered in the infosystem:"
echo "<pre>"
set -x
ftsURL=`lcg-infosites --vo $SAME_VO fts | grep $nodeName | head -n 1`
set +x
echo "FTS URL: $ftsURL"
echo "</pre>"
echo "summary: $ftsURL"
echo $ftsURL > ftsURL
if [ "x$ftsURL" == "x" ] ; then
    exit $SAME_ERROR
else
    exit $SAME_OK
fi

#****