#!/bin/bash
#****** gRB/gRB-sft-cancel
# NAME
# gRB-sft-cancel - checks:
# * glite-wms-job-delegate-proxy
# * glite-wms-job-submit
# * glite-wms-job-cancel
#
# AUTHOR
#
# Malgorzata Krakowian
#
# LAST UPDATED
#
# 9.11.2007
#
# LANGUAGE
#
# bash 
#
# SOURCE


. $SAME_SENSOR_HOME/config.sh

log="gRB-sft-check.log"
centralCE=`cat centralCE`
inMaintenance=`cat inMaintenance`

if [ "$1" != "--publish" ]; then
    siteName=$1
    nodeName=$2
    rm -f $log testjob-cancel.jid glite_wms-cancel.conf testjob-cancel.jdl
    echo "<h2>Generating JDL file:</h2>" >> $log
    sed  -e "s/<centralCE>/$centralCE/g" $SAME_SENSOR_HOME/testjob.jdl > testjob-cancel.jdl
    echo "<pre>" >> $log
    cat testjob-cancel.jdl >> $log
    echo "</pre>" >> $log
    echo "<h2>Generating glite_wms.conf file:</h2>" >> $log
    sed  -e "s/<nodeName>/$nodeName/g" -e "s/<SAME_VO>/$SAME_VO/g" -e "s|<SAME_SENSOR_WORK>|$SAME_SENSOR_WORK|g"  $SAME_SENSOR_HOME/glite_wms.conf > glite_wms-cancel.conf
    echo "<pre>" >> $log
    cat glite_wms-cancel.conf >> $log
    echo "</pre>" >> $log

    echo "<h2>Glite-wms-job-delegate-proxy</h2>" >> $log
    echo "<pre>" >> $log
    exec 3>&1 4>&2 1>>$log 2>&1
    set -x
    $JOB_DELEGATE_CMD  -d $nodeName -c glite_wms-cancel.conf 
    RESULT=$?
    set +x
    exec 1>&- 1>&3 2>&4 3>&- 4>&-
    echo "</pre>" >> $log
    if [ "$RESULT" != "0" ] ; then
	   echo "Proxy delegation failed! Check the Resource Broker" >> $log
	   echo "summary: DelegationError" >> $log
	   cat $log
	   grep -q "System load is too high" $log
           if [ "$?" == "0" ]; then
        	exit $SAME_WARNING
   	   fi

       	   rm -f $log testjob-cancel.jid glite_wms-cancel.conf testjob-cancel.jdl 
	   exit $SAME_ERROR
    fi


    echo "<h2>Glite-wms-job-submit</h2>" >> $log
    echo "<pre>" >> $log
    exec 3>&1 4>&2 1>>$log 2>&1
    set -x
    $JOB_SUBMIT_CMD  -d $nodeName -c glite_wms-cancel.conf -o testjob-cancel.jid testjob-cancel.jdl
    set +x
    exec 1>&- 1>&3 2>&4 3>&- 4>&-
    echo "</pre>" >> $log
    if [ ! -e testjob-cancel.jid ] ; then
    	echo "Job submission failed! Check the Resource Broker" >> $log
	   echo "summary: SubmitError" >> $log
	   cat $log
	   grep -q "System load is too high" $log
           if [ "$?" == "0" ]; then
        	exit $SAME_WARNING
   	   fi
       	   rm -f $log testjob-cancel.jid glite_wms-cancel.conf  testjob-cancel.jdl
	   exit $SAME_ERROR
    fi


    echo "<h2>Glite-wms-job-cancel</h2>" >> $log
    echo "<pre>" >> $log
    exec 3>&1 4>&2 1>>$log 2>&1
    set -x
    $JOB_CANCEL_CMD  --logfile cancel.log -i testjob-cancel.jid 
    RESULT=$?
    set +x
    exec 1>&- 1>&3 2>&4 3>&- 4>&-
    echo "</pre>" >> $log

    if [ "$RESULT" != "0"  -a ! "`grep "Error - Cancel not allowed" cancel.log`" ] ; then
	   echo "Job cancel failed! Check the Resource Broker" >> $log
	   echo "summary: CancelError" >> $log
	   cat $log
	   grep -q "System load is too high" $log
           if [ "$?" == "0" ]; then
        	exit $SAME_WARNING
   	   fi
           rm -f $log testjob-cancel.jid glite_wms-cancel.conf testjob-cancel.jdl cancel.log
	   exit $SAME_ERROR
    fi
    cat $log
    rm -f $log testjob-cancel.jid glite_wms-cancel.conf testjob-cancel.jdl cancel.log
    exit $SAME_OK 
fi
exit 0
#****
