#!/bin/bash
#****** gRB/gRB-sft-listmatch
# NAME
# gRB-sft-listmatch - checks:
# * glite-wms-job-delegate-proxy
# * glite-wms-job-list-match
#
# AUTHOR
#
# Malgorzata Krakowian
#
# LAST UPDATED
#
# 2007-11-09
#
# LANGUAGE
#
# bash 
#
# SOURCE


. $SAME_SENSOR_HOME/config.sh

log="gRB-sft-listmatch.log"
centralCE=`cat centralCE`
inMaintenance=`cat inMaintenance`

if [ "$1" != "--publish" ]; then
    siteName=$1
    nodeName=$2
    rm -f $log glite_wms-listmatch.conf testjob-listmatch.jdl
    echo "<h2>Generating JDL file:</h2>" >> $log
    grep -v Requirements $SAME_SENSOR_HOME/testjob.jdl > testjob-listmatch.jdl
    echo "<pre>" >> $log
    cat testjob-listmatch.jdl >> $log
    echo "</pre>" >> $log
    echo "<h2>Generating glite_wms-listmatch.conf file:</h2>" >> $log
    sed  -e "s/<nodeName>/$nodeName/g" -e "s/<SAME_VO>/$SAME_VO/g" -e "s|<SAME_SENSOR_WORK>|$SAME_SENSOR_WORK|g"  $SAME_SENSOR_HOME/glite_wms.conf  > glite_wms-listmatch.conf 
    echo "<pre>" >> $log
    cat glite_wms-listmatch.conf  >> $log
    echo "</pre>" >> $log
    echo "<h2>Glite-wms-job-delegate-proxy</h2>" >> $log
    echo "<pre>" >> $log
    exec 3>&1 4>&2 1>>$log 2>&1
    set -x
    $JOB_DELEGATE_CMD  -d $nodeName -c glite_wms-listmatch.conf 
    RESULT=$?
    set +x
    exec 1>&- 1>&3 2>&4 3>&- 4>&-
    echo "</pre>" >> $log
    if [ "$RESULT" != "0" ] ; then
	   echo "Proxy delegation failed! Check the Resource Broker" >> $log
	   echo "summary: DelegationError" >> $log
	   cat $log
	   grep -q "System load is too high" $log
           if [ "$?" == "0" ]; then
        	exit $SAME_WARNING
   	   fi

       	   rm -f $log testjob-cancel.jid glite_wms-cancel.conf testjob-cancel.jdl 
	   exit $SAME_ERROR
    fi


    echo "<h2>Glite-wms-job-list-match</h2>" >> $log
    echo "<pre>" >> $log
    exec 3>&1 4>&2 1>>$log 2>&1
    set -x
    $JOB_LISTMATCH_CMD -d $nodeName -c glite_wms-listmatch.conf  testjob-listmatch.jdl
    RESULT=$?
    set +x
    exec 1>&- 1>&3 2>&4 3>&- 4>&-
    echo "</pre>" >> $log
    if [ "$RESULT" != "0" ] ; then
	echo "Job listmatch failed! Check the Resource Broker" >> $log
	echo "summary: listmatchError" >> $log
	cat $log
	grep -q "System load is too high" $log
        if [ "$?" == "0" ]; then
            exit $SAME_WARNING
        fi
        rm -f $log glite_wms-listmatch.conf  testjob-listmatch.jdl
	exit $SAME_ERROR
    fi
    grep failure $log >/dev/null
    RESULT=$?
    if [ "$RESULT" == "0" ] ; then
  	echo "Job listmatch failed! Check the Resource Broker" >> $log
	echo "summary: listmatchError" >> $log
	cat $log
        rm -f $log glite_wms-listmatch.conf  testjob-listmatch.jdl
	exit $SAME_ERROR
    fi 
    cat $log
    rm -f $log glite_wms-listmatch.conf  testjob-listmatch.jdl
    exit $SAME_OK 
fi
exit 0
#****
