#!/bin/bash
export SAM_HOME=/afs/cern.ch/user/s/santinel/scratch0/SAM/same/client
source /afs/cern.ch/project/gd/LCG-share/sl4/etc/profile.d/grid-env.sh 
cat /afs/cern.ch/user/s/santinel/private/pas | voms-proxy-init --voms lhcb:/lhcb/Role=production -pwstdin
cd $SAM_HOME
#for i in `cat /afs/cern.ch/user/s/santinel/scratch0/grid/lfc/LFC-HOSTs`;
for i in `cat /afs/cern.ch/user/s/santinel/scratch0/grid/lfc/mirrors`;
do echo $i;
  bin/same-exec LFC_L nodename=$i
done
  bin/same-exec LFC_C nodename=prod-lfc-lhcb-central.cern.ch	

 
