#!/bin/sh

function canonicalize
{
  cd -P -- "$(dirname -- "$1")" &&
  printf '%s\n' "$(pwd -P)/$(basename -- "$1")"
}
basedir=`canonicalize $0`
basedir=`dirname $basedir`
basedir=`canonicalize $basedir/..`
ext_ver="v6r5p4"

DIRACPLAT=$1
PYTHON_VERSION_TWODIGIT=$2
PYTHON_CONFIG_VERSION=$3

cd $basedir

if ! [ -r $basedir/InstallArea/$CMTCONFIG/lib ]; then
  mkdir $basedir/InstallArea/$CMTCONFIG/lib
fi

tarnamehttp=http://cern.ch/lhcbproject/dist/DIRAC3/installSource/Externals-client-${ext_ver}-${DIRACPLAT}-python${PYTHON_VERSION_TWODIGIT}.tar.gz
tarname=${TMPDIR}/Externals-client-${ext_ver}-${DIRACPLAT}-python${PYTHON_VERSION_TWODIGIT}.tar.gz

curl -k -L -o $tarname $tarnamehttp

# Get GSI

fullname=`tar ztvf $tarname | grep GSI | grep '__init__.py' | tail -1 | awk '{print $6}'`
fullpath=`dirname $fullname`

tar zxvf $tarname $fullpath
tar zxvf $tarname -C $basedir/InstallArea/$CMTCONFIG/lib --strip-components 2 ${DIRACPLAT}/lib/libssl* --strip-components 2 ${DIRACPLAT}/lib/libcrypto*

if ! [ -r $basedir/InstallArea/$CMTCONFIG/python${PYTHON_CONFIG_VERSION} ]; then
  mkdir $basedir/InstallArea/$CMTCONFIG/python${PYTHON_CONFIG_VERSION}
fi

mv $fullpath $basedir/InstallArea/$CMTCONFIG/python${PYTHON_CONFIG_VERSION}/

# get pyparsing
fullname=`tar ztvf $tarname | grep pyparsing | grep egg | tail -1 | awk '{print $6}'`
if ! [ -e $fullname ]; then
  tar zxvf $tarname $fullname
  mv $fullname $basedir/InstallArea/$CMTCONFIG/python${PYTHON_CONFIG_VERSION}
fi
